### ISSUE TITLE
Changing the end-user-ui context

### ISSUE THREAD

**Issue by calleggr** [ForgeRock/end-user-ui#21]
When using this to customize the end-user-ui for IDM, changing the context in project-dir/conf/ui.context-enduser.json does not work

**Comment by jsonisathingy** [comment]
Are you referring to the context of where enduser is located or the context of where IDM is related? That file you are referencing controls where IDM serves the enduser project. You would still need to replace the existing enduser folder contents with a newly generated content (from this project) if you wanted to make use of the IDM hosted UI. 

Let me know if that helps at all, if not could you provide some steps for what you are trying to achieve?

**Comment by calleggr** [comment]
We are trying to change the context of the end user UI to "/profile".  We are following the steps from this repo to build the end-user UI and replace the enduser folder contents.  When we restart openidm the end-user UI does not load and if you check the network trace there are 404 errors for a bunch of JS files called "chunks"

Thanks,
Greg

**Comment by calleggr** [comment]
![image](https://user-images.githubusercontent.com/8797114/78192210-4c4a8280-743d-11ea-8441-eaacce42e104.png)

**Comment by jsonisathingy** [comment]
Looks like in the vue.config.js file the  `publicPath: './',` property got removed. If you add that line in you should be able to build deployable copies to any IDM context. I will put up a PR on our side to add this back in.

**Comment by calleggr** [comment]
Thank you!

**Comment by jsonisathingy** [comment]
Fix merged https://github.com/ForgeRock/end-user-ui/commit/87186e126daeb3f4c503a867ddfe1a3095ee9b28 (sorry PR requests go through our stash and are mirrored out to github after merge).
