### ISSUE TITLE
Issue when starting development server

### ISSUE THREAD

**Issue by gsoba1** [ForgeRock/end-user-ui#22]
Sorry if this is the not the right place to find an answer for this issue but I'm having an issue when trying to start the development server.

This is my output:
> Identity-Management@2.0.0 dev C:\IDM\end-user-ui-master
> vue-cli-service serve

 INFO  Starting development server...
 78% module and chunk tree optimization optimize-tree

It just hangs here at 78% and was wondering if this is something on my end or its an actual issue.

Additional context: I can start the vue UI fine and i do have 1 low severity vulnerability in my packages.

 === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Low             Prototype Pollution

  Package         minimist

  Patched in      >=0.2.1 <1.0.0 || >=1.2.3

  Dependency of   @vue/cli-plugin-unit-mocha [dev]

  Path            @vue/cli-plugin-unit-mocha > mocha > mkdirp > minimist

  More info       https://npmjs.com/advisories/1179

Any feedback would be greatly appreciated!

**Comment by jsonisathingy** [comment]
Did you download or clone the repo? We are making use of a plugin that reads git information to better help QA with build hashes. So if you download this you would need to remove that file. 

https://github.com/ForgeRock/end-user-ui/blob/master/vue.config.js#L2

**Comment by gsoba1** [comment]
Oh i see in my case i downloaded the repo so your saying I would need to delete the vue.config.js file or the file that has that git plugin?

Would you recommend just cloning to avoid this issue entirely?

My versions:
node: v12.16.1
npm: 6.14.4

**Comment by gsoba1** [comment]
Update: I cloned the repo instead of downloading and the problem persisted

**Comment by jsonisathingy** [comment]
Could you try deleting your node folder and attempt another npm install -> npm run dev. I downloaded a fresh copy of the project and cloned it. 

NPM: 6.13.4
Node: v13.5.0

**Comment by gsoba1** [comment]
Oh that worked! I thought I had git installed but it wasn't.

Thank you so much for all your help!!

**Comment by gsoba1** [comment]
One last question If I am working with modifying the user list view what folder should i be looking in?

Pic for context:
![userlist-enduser](https://user-images.githubusercontent.com/16962848/78268897-e3afe400-74d6-11ea-9b47-332e68a9044a.png)

**Comment by jsonisathingy** [comment]
Anything related to delegated admin is under `src/components/access`. The list page specifically is the index.vue file in that folder.

**Comment by gsoba1** [comment]
Awesome thanks for all your help!!!

**Comment by gsoba1** [comment]
Hey would there be any criteria that a custom user attribute would have to satisfy in order to appear on the end user view? 

I'm having issues having trouble adding custom attribute columns to the user list table custom attributes. 

I was successful adding a new column titled "email attributes" but this was the only attribute i was able to view in the end user ui. Any other custom attribute fails to show up.

**Comment by jsonisathingy** [comment]
Is this in regards to delegated admin? Could you send a screenshot so I can be sure of what section of the UI you are referring to.

**Comment by gsoba1** [comment]
Yes this is in reference to delegated admin.

Heres the screenshot:
![image](https://user-images.githubusercontent.com/16962848/78592710-7b813b00-7813-11ea-947a-56c152632300.png)

**Comment by gsoba1** [comment]
Email Aliases and Employee Location code are custom fields but any other field i try and add dont pop up

Admin user list for context:
![image](https://user-images.githubusercontent.com/16962848/78592991-e6327680-7813-11ea-855e-cfe4d375a67a.png)

**Comment by gsoba1** [comment]
Here is the config for emailAliases and testThingy:

"allEmailAliases" : {
                        "title" : "Email Aliases",
                        "type" : "string",
                        "viewable" : true,
                        "searchable" : true,
                        "userEditable" : true
                    }

"testThingy" : {
                        "title" : "testThingy",
                        "type" : "string",
                        "viewable" : true,
                        "searchable" : true,
                        "userEditable" : true
                    },

**Comment by gsoba1** [comment]
Never mind it was a dumb mistake.

I forgot to enable viewership of those attributes in the delegated admin roles.

Thank you!

**Comment by jsonisathingy** [comment]
Ah, gotcha, glad you figured it out!

**Comment by gsoba1** [comment]
Hi, running into a new issue where none of my enduser project instances are able to run build.

This is the output that I'm getting:

![image](https://user-images.githubusercontent.com/16962848/79228714-eba14980-7e2f-11ea-8873-b0ff1770fb83.png)

And this is the context of the specified log file:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\gsoba\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.12.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle Identity-Management@2.0.0~prebuild: Identity-Management@2.0.0
6 info lifecycle Identity-Management@2.0.0~build: Identity-Management@2.0.0
7 verbose lifecycle Identity-Management@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle Identity-Management@2.0.0~build: PATH: C:\Users\gsoba\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\gsoba\OneDrive - Touro College\Desktop\touro-hubcity\touro\end-user-ui\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jre7\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\IBM\Client Access\Emulator;C:\Program Files (x86)\IBM\Client Access\Shared;C:\Program Files (x86)\IBM\Client Access\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Users\gsoba\AppData\Local\Microsoft\WindowsApps;C:\Users\gsoba\AppData\Local\GitHubDesktop\bin;C:\Users\gsoba\AppData\Roaming\npm
9 verbose lifecycle Identity-Management@2.0.0~build: CWD: C:\Users\gsoba\OneDrive - Touro College\Desktop\touro-hubcity\touro\end-user-ui
10 silly lifecycle Identity-Management@2.0.0~build: Args: [ '/d /s /c', 'vue-cli-service build' ]
11 silly lifecycle Identity-Management@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle Identity-Management@2.0.0~build: Failed to exec build script
13 verbose stack Error: Identity-Management@2.0.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\gsoba\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\gsoba\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid Identity-Management@2.0.0
15 verbose cwd C:\Users\gsoba\OneDrive - Touro College\Desktop\touro-hubcity\touro\end-user-ui
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\gsoba\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v13.12.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error Identity-Management@2.0.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the Identity-Management@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Any familiarity with this issue?

Thanks

**Comment by jsonisathingy** [comment]
Hm the quickest fix you can attempt is to delete the node modules folder and try to npm install and then start the development server. We didn't include a package lock file with this project initially and have occasionally seen weirdness like this.

**Comment by jsonisathingy** [comment]
Also if you downloaded and not cloned will need to remove https://github.com/ForgeRock/end-user-ui/blob/master/vue.config.js     `GitRevisionPlugin = require('git-revision-webpack-plugin');`

**Comment by gsoba1** [comment]
Ah yes looks like i forgot to get rid of the git plugin.

Thanks again!!

**Comment by gsoba1** [comment]
Running into an issue where i can't get Array properties to show up on the delegated admin view and I noticed that it doesn't seem like they are supported am i correct?

Also I am having trouble locating what file correlates to the **user detail page** that you can get to by clicking on a user on the delegated admin user list.

**Comment by jsonisathingy** [comment]
All of the delegated admin work is located under the `src/components/access`. 

1) In edit resource if you look around line 29 you will see a v-for. The properties in there are where it is generated. You are correct in assuming we don't by default handle arrays. Though it wouldn't be hard to add another block there to generate arrays as you see fit. 

2) EditResource.vue is the file you are looking for the DA dialog for adding a new resource.

**Comment by gsoba1** [comment]
Thank you for all the help you've given thus far, can't thank you enough! 

I was wondering if you've had any experience with CORS issues and if there were any recommended routes for either making a rest call to a vendor site over rest on the end user side or methods for accomplishing this through a custom IDM endpoint? Or the correct forum to pose these questions?
