### ISSUE TITLE
Typo in en.json

### ISSUE THREAD

**Issue by calleggr** [ForgeRock/end-user-ui#23]
https://github.com/ForgeRock/end-user-ui/blob/master/src/locales/en.json#L276

Should be single quote not double in "can't"

**Comment by jsonisathingy** [comment]
Will file a ticket on our side and update this issue when it is committed. Thanks for reporting.

**Comment by jsonisathingy** [comment]
This issue is now fixed with https://github.com/ForgeRock/end-user-ui/commit/018a8428a8475e360b88c09fb2e5cf538084bc10 commit
